### ISSUE TITLE
"unread" reminders badge

### ISSUE THREAD

**Issue by ulich** [peiche/PanelViewKeep#6]
If you set up a reminder on a task in Keep, chrome displays a notification when the time is up. But if you miss the notification, you might forget the reminder. It would be really helpful if the number of "unread" reminders were displayed on the icon of your extension (like google mail extension does for unread emails)

I know there is no official API of Keep, but maybe there is some way?

**Comment by peiche** [comment]
There are ways to inspect the page to grab the number of reminders, but it would be a hack. Due to the number of times Google has changed Keep's interface, I opted (from version 3 onward) to keep the number of hacks used down to a minimum.
